### ISSUE TITLE
Configuration error message after update to 4.0.5

### ISSUE THREAD

**Issue by ghost** [sadikoff/i18n-form-bundle#3]
After updating to v4.0.5 I get the following error message:

```
In ScalarNode.php line 36:
Invalid type for path "i18n_form.locales.0". Expected scalar, but got array.
```
My configuration file:

```yaml
i18n_form:
    locales: [de, en]
    default_locale: de
    required_locales: [de]
```

When I comment the 'locales' line, the error message changes to:
```
In ScalarNode.php line 36:
Invalid type for path "i18n_form.required_locales.0". Expected scalar, but got array.
```

In the previous version the configuration was working without any issues.
